version: "3.7"

volumes:
  elastic_data:

networks:
  elastic_network:
  
services:
  elastic:
    container_name: elastic
    image: blacktop/elasticsearch:latest
    ports:
      - "9200:9200"
    networks:
      - elastic_network
    restart: unless-stopped
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana_1:
    container_name: kibana_1
    image: blacktop/kibana:latest
    ports:
      - "5601:5601"
    networks:
      - elastic_network
    depends_on:
      - elastic
    restart: unless-stopped
    environment:
      - elasticsearch.hosts=["http://elastic:9200"]